### ISSUE TITLE
What is the difference between generate-permit-list --expected-ori "either" and "both"?

### ISSUE THREAD

**Issue by ColeWunderlich** [COMBINE-lab/alevin-fry#107]
I noticed that there are`either` and `both` options for the `--expected-ori` flag when running `generate-permit-list`.  Is there a difference between these two options, or do they both allow for retaining forward and rc mappings?

**Comment by rob-p** [comment]
Hi @ColeWunderlich,

  Here `either` is just a synonym for `both`.  They have exactly the same effect in the code, and if the string passed to `--expected-ori` is `either` or `both`, then both forward and rc mappings will be retained.

**Comment by ColeWunderlich** [comment]
Awesome, thanks @rob-p!
