### ISSUE TITLE
Difference in expression when used salmon-alevin vs alevin-fry

### ISSUE THREAD

**Issue by sdr08** [COMBINE-lab/alevin-fry#109]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Dear Alevin-Fry Team,<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><o:p> </o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">I’m given a 10x v2 5’ data set to identify sense and antisense transcript abundances.<span class="Apple-converted-space"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">I used salmon alevin 1.10.0 with this dataset but decided to use alevin-fry since I was getting very few reads (&lt;100) mapping to an antisense transcript that’s expected to have ~2000 reads alignment from cellranger bam file. The sense transcript of interest was getting ~4000 reads mapping from this method.<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">I used the same reference to generate a direct reference index from simpleaf and this method gave similar read alignment to the antisense as seen with the bam (~1200) but now I don’t get any alignment to the sense transcript with cr-like and parsimony resolutions. I used the previously build salmon index with the parsimony resolution as well but still didn’t get any reads aligning to the sense transcript.<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><o:p> </o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Salmon alevin 1.10.0 commands:<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">salmon alevin -l ISF -i index -1 read1.fastqs -2 read2.fastqs--chromium -p 32 --whitelist WHITELIST --tgMap TXMAP<span class="Apple-converted-space"> </span><span> </span>--dumpFeatures -o salmon_alevin<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><o:p> </o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">alevin-fry 0.8.1 commands:<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">salmon alevin -lISF --chromium -1 read1.fastqs -2 read2.fastqs -o SAMPLE_alevin -i index -p 32 --sketch<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">alevin-fry generate-permit-list --input SAMPLE_alevin --expected-ori fw --output-dir SAMPLE_fry --unfiltered-pl WHITELIST<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">alevin-fry collate -i SAMPLE_fry -r SAMPLE_alevin -t 32<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">alevin-fry quant -i SAMPLE_fry -m TXMAP -t 32 -r parsimony -o SAMPLE_fry<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><o:p> </o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Summary of the alignment counts seen with the different methods used.<o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><o:p> </o:p></p>

Transcript | Salmon-alevin 1.10.0 nodecoy ref | Alevin-fry 0.8.1 simpleaf index direct ref | Alevin-fry 0.8.1 nodecoy ref
-- | -- | -- | --
Antisense transcript | <100 | ~1200 | ~1200
Sense transcript | ~4000 | No alignment | No alignment

<p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><o:p> </o:p></p><p class="MsoNormal" style="margin: 0in; font-size: medium; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Any help is greatly appreciated and thank you for the great software.<o:p></o:p></p></html>

**Comment by rob-p** [comment]
Hi @sdr08,

  (Ping @DongzeHE) Can you give some more details about the specific data and indices?  If you ran with `simpleaf` directly then it will have built a splici index and so you'll have to think about how you wish to load the expression matrix (i.e. which of the layers).  This is less of an issue with the direct ref (though that's going to force things to map against the spliced transcripts even when that might not be the best explanation sometimes).  You will also want to look at what type of directional filtering you are applying.  Finally, were there any messages in the log that look relevant?

Thanks,
Rob

**Comment by sdr08** [comment]
Thank you for your quick response. 
Indices were build for refseq transcripts with the addition of few manually annotated antisense transcripts without any decoys. Following are the commands used to create the indices.

index1: salmon 1.10.0
salmon index -t ref.fna -p 32 -i index > salmon.log

index2: simpleaf index

simpleaf index --output . --ref-seq ref.fna --threads 32

I used both index1 and index2 with alevin-fry. 
I used fishpond library loadFry function to load the fry data.
I did not apply any directional filtering and couldn’t find any parameter in alevin-fry to do that. Is there any parameter that does directional filtering? I didn't find any warnings etc. in the log files either.

**Comment by rob-p** [comment]
Hi @sdr08,

  Ok, so given that you are doing the direct reference indexing rather that building a splici/spliceu reference, the differences you observe are unlikely to have anything to do with the USA (Unspliced / Spliced / Ambiguous) counts.

  Can you provide the details about the RefSeq transcriptome you used (i.e. what organism and a link to the reference).  The manually added transcripts are unlikely to be problematic so we wouldn't need them to reproduce.  

  Is the read data you are processing public or private?

  There are parameters that do directional filtering.  When you run `simpleaf quant` it is this parameter:

```
-d, --expected-ori <EXPECTED_ORI>      The expected direction/orientation of alignments in the chemistry being processed. If not provided, will default to `fw` for 10xv2/10xv3, otherwise `both` [possible
                                         values: fw, rc, both]
```

  When using `alevin-fry` directly, this is the `--expected-ori` argument that is passed during the `generate-permit-list` phase of execution.

  Are you using the same permit-list generation method in both workflows (e.g. using an external permit list, or using knee finding, etc.)?

**Comment by sdr08** [comment]
I used the human refseq transcripts.
[GCF_000001405.39_GRCh38.p13_rna.fna.gz](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_rna.fna.gz)

This is a private dataset. I ran the analysis with the expected-ori "both" option but still getting similar results. I'm using an external permit list which are the barcode files from cell ranger and used the same lists for both Alevin whitelist and alevin-fry unfiltered-pl.

**Comment by rob-p** [comment]
Any thoughts here @DongzeHE?  I can't see any reason why the counts would look very different if the direct reference is being used and if the permit list is the external 10x one (though these tools use the permit list differently; alevin treats it as a list of known, believed high-quality cells and alevin-fry treats it as a list of potential barcodes to be corrected against).

@sdr08, regarding:

> I want to correct that the table I have is for cell counts with expression >0 for each transcript.

Can you say how many cells are detected by each method (i.e. the size of the output matrices)?


In general it's hard to replicate the behavior without being able to process the dataset.  Are there any other (publicly available) datasets where you've seen this behavior?

Thanks!

**Comment by sdr08** [comment]
Hi @rob-p,

I wasn't able to find any publicly available data, but was able to get permission from the PI to share the data with you. I will share the data with you in a few days. 

Thank you.

**Comment by sdr08** [comment]
Hi @rob-p,

I can use Globus to share the data. If you have a Globus account, could you please share the user name?
Thank you

**Comment by rob-p** [comment]
Hi @sdr08,

  Great, you can share with nomad@umd.edu on globus.

Thanks,
Rob

**Comment by sdr08** [comment]
Hi @rob-p,

I sent you an email with the link. Thank you again for looking in to this.

**Comment by rob-p** [comment]
Hi @sdr08,

  I've now been able to process some of the data (it's a lot and so I just wanted to try one pair of files first), and, interestingly, I'm not seeing this behavior.  I'll note that I tried the direct-ref approach given the files you shared.  However, that approach has some issues since (1) it doesn't have the advantage of USA mode since the transcriptome was not generated from the genome and GTF and (2) it will be quantifying at the transcript level as the txmap provided maps each transcript to itself.

  Nonetheless, it still provides a valid quantification in my hands.  My processing was as follows:

Indexing:
```
simpleaf index -t 16 -k 31 -o index --ref-seq <reference_you_shared>.fna
```

Quant:
```
simpleaf quant -c 1{b[16]u[10]x:}2{r:} -1 <read1>.fastq.gz -2 <read2>.fastq.gz -t 16 -m txmap.tsv -r parsimony-em -u $ALEVIN_FRY_HOMEplist/10x_v2_permit.txt -o QUANT -i index/index
```

I can provide the specific filenames used if you want (I wasn't sure if they contain any relevant information, so I've redacted them above).  Nonetheless, this produces plenty of output:

Head of the output count matrix:
```
%%MatrixMarket matrix coordinate real general
% written by sprs
74857 159072 61343768
```

Are there any obvious differences between the commands I'm issuing above and what you are using?

Best,
Rob

```

**Comment by sdr08** [comment]
Hi @rob-p,

Thank you so much for the commands, this worked for me. Now I get cell counts for the specific transcripts we are interested in.
The major difference in what I did and your commands are, I used the commands separately with -lISF --chromium and also provided a white list. 
Thank you again!
