### ISSUE TITLE
Unmaintained dependency used by alevin fry

### ISSUE THREAD

**Issue by kbipinkumar** [COMBINE-lab/alevin-fry#114]
while building alevin-fry cargo gives following output

```bash
   Compiling alevin-fry v0.8.1 (/build/alevin-fry/src/alevin-fry-0.8.1)
    Finished release [optimized] target(s) in 6m 42s
warning: the following packages contain code that will be rejected by a future version of Rust: buf_redux v0.8.4
```

its seems buf_redux  dependency is [unmaintained ](https://github.com/rustsec/advisory-db/pull/1614). However there is drop in replacement for buf_redux called [buffer-redux](https://crates.io/crates/). it would be great if the unmaintained dependency is replaced with a maintained one.

**Comment by rob-p** [comment]
Thanks!  It's a recursive dependency, and I've updated the dependency that uses this (they replaced it upstream).  I also took this opportunity to update some other dependencies.  A new release is pending.
