### ISSUE TITLE
The barcode or umi spans multi reads

### ISSUE THREAD

**Issue by wangjiawen2013** [COMBINE-lab/alevin-fry#131]
Hi,
It is said that (https://combine-lab.github.io/alevin-fry-tutorials/2021/custom-geo/)

you can use the --custom-geometry flag. Cases where it can be used:

* case 1: The barcode or umi spans both reads
* case 2: The barcode or umi has variable length
* case 3: There is a fixed sequence in the read(s)

But there are no examples on case1 (The barcode or umi spans both reads) in the tutorial. Could you give an example of this case ?

Besides, the barcode we are using are 12 bp, the first 6bp are in I1, the second 6bp are in I2, and the umi are in read1(3 bp umi + 32bp biological read + 3bp umi). Of course we can concat I1 and I2 and then apply case1. I am wondering that can we use I1, I2, read2 directly without merging I1 and I2 (in this case the barcode or umi spans three (not two) reads)?  Here is the structure of our data:
![image](https://github.com/COMBINE-lab/alevin-fry/assets/29703450/93141f0b-f6b4-4702-bc11-8f26c48d9841)

**Comment by wangjiawen2013** [comment]
There are two parameters when using simpleaf index:

-k, --kmer-length <KMER_LENGTH>  the value of k to be used to construct the index [default: 31]
-r, --rlen <RLEN>            the target read length the splici index will be built for

Are there any correlations or mutual limitations between -k and -r ? what does "target read length" mean ? Is it the whole length of reads or reads excluding umi and barcode and other irrelevant nucledotides ?  If the reads lenght is just 20bp (or 32bp in my case), how to set -k ?

**Comment by rob-p** [comment]
Hi @wangjiawen2013,

  The `-k` length and the `-r` length are largely independent. The `-r` should be approximately equal to the length of the longest end of a biological read (after the barcode and UMI are removed).  So, e.g. if you had chromium v3 data with 91bp reads, you'd set `-r 91`.  However, the results are highly robust to the exact choice of `-r` (we explore that in the `alevin-fry` paper).
  
  The `-k` length is the size of the k-mers that are used to index the reference.  The larger `k` is set, the faster mapping is in general, but the higher the chance that a sufficient number of errors may cause a read to not map.  In general, the default value of 31 works quite well for common modern read lengths (e.g. 90-150 bases). K larger than 31 isn't supported. For short reads (e.g. 50), you may want to make `k` a bit smaller (e.g. 23 or 25). But, generally, results are fairly robust to the choice of `k`.

**Comment by wangjiawen2013** [comment]
@rob-p 
Thanks! How about the first question ?

> Hi, It is said that (https://combine-lab.github.io/alevin-fry-tutorials/2021/custom-geo/)
> 
> you can use the --custom-geometry flag. Cases where it can be used:
> 
> * case 1: The barcode or umi spans both reads
> * case 2: The barcode or umi has variable length
> * case 3: There is a fixed sequence in the read(s)
> 
> But there are no examples on case1 (The barcode or umi spans both reads) in the tutorial. Could you give an example of this case ?
> 
> Besides, the barcode we are using are 12 bp, the first 6bp are in I1, the second 6bp are in I2, and the umi are in read1(3 bp umi + 32bp biological read + 3bp umi). Of course we can concat I1 and I2 and then apply case1. I am wondering that can we use I1, I2, read2 directly without merging I1 and I2 (in this case the barcode or umi spans three (not two) reads)? Here is the structure of our data: ![image](https://private-user-images.githubusercontent.com/29703450/301105476-93141f0b-f6b4-4702-bc11-8f26c48d9841.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTM5MDQsIm5iZiI6MTcwNjc1MzYwNCwicGF0aCI6Ii8yOTcwMzQ1MC8zMDExMDU0NzYtOTMxNDFmMGItZjZiNC00NzAyLWJjMTEtOGYyNmM0OGQ5ODQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAyMTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZGY2ZmY1ODMwZTdmZWRjZjEzMDU4ODhkY2ZhYzVhMmVmMGExNjU4ZTJlYWRmODlkMjE2NzI5NjQ5NWQ3NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kRYHcHq0PbajSXhd7XrvCBzBnW__rlJpySPDKKIBSwE)

**Comment by rob-p** [comment]
Hi @wangjiawen2013,

  Could you share a small sample of the reads so that we could test the relevant geometry flag and make sure it's working properly?  Regarding the case you bring up where there are more than 2 files that encode the read + bc + UMI (e.g. the I1 and I2 files), that isn't directly supported because the parser parses paired-end sequencing data.  However, I think it might be possible to perform the concatenation in a "streaming" fashion so that you don't have to spend time and disk space creating intermediate files. For example using input redirection and maybe `awk`.  As I mentioned above, if you can share a small subset of the data, we can help find the most direct way to process it with simpleaf, and the right geometry flag. Also cc @DongzeHE.

Best,
Rob

**Comment by wangjiawen2013** [comment]
I have found a good way, thanks!

**Comment by rob-p** [comment]
Great! Can you share what the basic structure of the solution was? That way we can add it to the docs or a FAQ in case someone runs into a similar issue.

Thanks!
Rob

**Comment by wangjiawen2013** [comment]
In my case, all the barcodes in I1.fastq is the same one, so I can neglect I1.
