### ISSUE TITLE
ExitStatus(unix_wait_status(6))

### ISSUE THREAD

**Issue by Anto9393** [COMBINE-lab/alevin-fry#138]
**I have had this problem when running the simpleaf quant, but I don't know how to solve it.**

```
(af) anto@NUBIAN:~/Dunja/Anto/AF_SAMPLE_DIR$ simpleaf quant --reads1 $reads1 --reads2 $reads2 --threads 18 --index IDX_DIR/index --chemistry 10xv2 --resolution cr-like --expected-ori fw --unfiltered-pl --t2g-m
ap IDX_DIR/index/t2g_3col.tsv --output AF_SAMPLE_DIR/pbmc1k_quant

2024-03-05T23:40:47.954352Z  INFO simpleaf::simpleaf_commands::quant: piscem map-sc cmd : /home/anto/anaconda3/envs/af/bin/piscem map-sc --index IDX_DIR/index/piscem_idx --threads 18 -o AF_SAMPLE_DIR/pbmc1k_quant/af_map --max-ec-card 4096 --skipping-strategy permissive --max-hit-occ 256 --max-hit-occ-recover 1024 --max-read-occ 2500 -1 FASTQ_DIR/SRR11442128_1.fastq.gz,FASTQ_DIR/SRR11442139_1.fastq.gz,FASTQ_DIR/SRR11442152_1.fastq.gz,FASTQ_DIR/SRR11442163_1.fastq.gz,FASTQ_DIR/SRR11442174_1.fastq.gz,FASTQ_DIR/SRR11442185_1.fastq.gz,FASTQ_DIR/SRR11442196_1.fastq.gz,FASTQ_DIR/SRR11442207_1.fastq.gz,FASTQ_DIR/SRR11442225_1.fastq.gz,FASTQ_DIR/SRR11442226_1.fastq.gz,FASTQ_DIR/SRR11442227_1.fastq.gz,FASTQ_DIR/SRR11442228_1.fastq.gz,FASTQ_DIR/SRR11442229_1.fastq.gz,FASTQ_DIR/SRR11442230_1.fastq.gz,FASTQ_DIR/SRR11442231_1.fastq.gz,FASTQ_DIR/SRR11442232_1.fastq.gz,FASTQ_DIR/SRR11442233_1.fastq.gz,FASTQ_DIR/SRR11442234_1.fastq.gz,FASTQ_DIR/SRR11442235_1.fastq.gz,FASTQ_DIR/SRR11442244_1.fastq.gz,FASTQ_DIR/SRR11442255_1.fastq.gz,FASTQ_DIR/SRR11442256_1.fastq.gz,FASTQ_DIR/SRR11442257_1.fastq.gz -2 FASTQ_DIR/SRR11442128_2.fastq.gz,FASTQ_DIR/SRR11442139_2.fastq.gz,FASTQ_DIR/SRR11442152_2.fastq.gz,FASTQ_DIR/SRR11442163_2.fastq.gz,FASTQ_DIR/SRR11442174_2.fastq.gz,FASTQ_DIR/SRR11442185_2.fastq.gz,FASTQ_DIR/SRR11442196_2.fastq.gz,FASTQ_DIR/SRR11442207_2.fastq.gz,FASTQ_DIR/SRR11442225_2.fastq.gz,FASTQ_DIR/SRR11442226_2.fastq.gz,FASTQ_DIR/SRR11442227_2.fastq.gz,FASTQ_DIR/SRR11442228_2.fastq.gz,FASTQ_DIR/SRR11442229_2.fastq.gz,FASTQ_DIR/SRR11442230_2.fastq.gz,FASTQ_DIR/SRR11442231_2.fastq.gz,FASTQ_DIR/SRR11442232_2.fastq.gz,FASTQ_DIR/SRR11442233_2.fastq.gz,FASTQ_DIR/SRR11442234_2.fastq.gz,FASTQ_DIR/SRR11442235_2.fastq.gz,FASTQ_DIR/SRR11442244_2.fastq.gz,FASTQ_DIR/SRR11442255_2.fastq.gz,FASTQ_DIR/SRR11442256_2.fastq.gz,FASTQ_DIR/SRR11442257_2.fastq.gz --geometry chromium_v2
2024-03-05T23:48:17.223557Z ERROR simpleaf::utils::prog_utils: command unsuccessful (signal: 6 (SIGABRT)): "/home/anto/anaconda3/envs/af/bin/piscem" "map-sc" "--index" "IDX_DIR/index/piscem_idx" "--threads" "18" "-o" "AF_SAMPLE_DIR/pbmc1k_quant/af_map" "--max-ec-card" "4096" "--skipping-strategy" "permissive" "--max-hit-occ" "256" "--max-hit-occ-recover" "1024" "--max-read-occ" "2500" "-1" "FASTQ_DIR/SRR11442128_1.fastq.gz,FASTQ_DIR/SRR11442139_1.fastq.gz,FASTQ_DIR/SRR11442152_1.fastq.gz,FASTQ_DIR/SRR11442163_1.fastq.gz,FASTQ_DIR/SRR11442174_1.fastq.gz,FASTQ_DIR/SRR11442185_1.fastq.gz,FASTQ_DIR/SRR11442196_1.fastq.gz,FASTQ_DIR/SRR11442207_1.fastq.gz,FASTQ_DIR/SRR11442225_1.fastq.gz,FASTQ_DIR/SRR11442226_1.fastq.gz,FASTQ_DIR/SRR11442227_1.fastq.gz,FASTQ_DIR/SRR11442228_1.fastq.gz,FASTQ_DIR/SRR11442229_1.fastq.gz,FASTQ_DIR/SRR11442230_1.fastq.gz,FASTQ_DIR/SRR11442231_1.fastq.gz,FASTQ_DIR/SRR11442232_1.fastq.gz,FASTQ_DIR/SRR11442233_1.fastq.gz,FASTQ_DIR/SRR11442234_1.fastq.gz,FASTQ_DIR/SRR11442235_1.fastq.gz,FASTQ_DIR/SRR11442244_1.fastq.gz,FASTQ_DIR/SRR11442255_1.fastq.gz,FASTQ_DIR/SRR11442256_1.fastq.gz,FASTQ_DIR/SRR11442257_1.fastq.gz" "-2" "FASTQ_DIR/SRR11442128_2.fastq.gz,FASTQ_DIR/SRR11442139_2.fastq.gz,FASTQ_DIR/SRR11442152_2.fastq.gz,FASTQ_DIR/SRR11442163_2.fastq.gz,FASTQ_DIR/SRR11442174_2.fastq.gz,FASTQ_DIR/SRR11442185_2.fastq.gz,FASTQ_DIR/SRR11442196_2.fastq.gz,FASTQ_DIR/SRR11442207_2.fastq.gz,FASTQ_DIR/SRR11442225_2.fastq.gz,FASTQ_DIR/SRR11442226_2.fastq.gz,FASTQ_DIR/SRR11442227_2.fastq.gz,FASTQ_DIR/SRR11442228_2.fastq.gz,FASTQ_DIR/SRR11442229_2.fastq.gz,FASTQ_DIR/SRR11442230_2.fastq.gz,FASTQ_DIR/SRR11442231_2.fastq.gz,FASTQ_DIR/SRR11442232_2.fastq.gz,FASTQ_DIR/SRR11442233_2.fastq.gz,FASTQ_DIR/SRR11442234_2.fastq.gz,FASTQ_DIR/SRR11442235_2.fastq.gz,FASTQ_DIR/SRR11442244_2.fastq.gz,FASTQ_DIR/SRR11442255_2.fastq.gz,FASTQ_DIR/SRR11442256_2.fastq.gz,FASTQ_DIR/SRR11442257_2.fastq.gz" "--geometry" "chromium_v2"

2024-03-05T23:48:17.223640Z ERROR simpleaf::utils::prog_utils: stderr :
====

2024-03-05T23:40:48.000699Z  INFO piscem: cmd: ["sc_ref_mapper", "-i", "IDX_DIR/index/piscem_idx", "-g", "chromium_v2", "-1", 
"FASTQ_DIR/SRR11442128_1.fastq.gz,FASTQ_DIR/SRR11442139_1.fastq.gz,FASTQ_DIR/SRR11442152_1.fastq.gz,FASTQ_DIR/SRR11442163_1.fastq.gz,FASTQ_DIR/SRR11442174_1.fastq.gz,FASTQ_DIR/SRR11442185_1.fastq.gz,FASTQ_DIR/SRR11442196_1.fastq.gz,FASTQ_DIR/SRR11442207_1.fastq.gz,FASTQ_DIR/SRR11442225_1.fastq.gz,FASTQ_DIR/SRR11442226_1.fastq.gz,FASTQ_DIR/SRR11442227_1.fastq.gz,FASTQ_DIR/SRR11442228_1.fastq.gz,FASTQ_DIR/SRR11442229_1.fastq.gz,FASTQ_DIR/SRR11442230_1.fastq.gz,FASTQ_DIR/SRR11442231_1.fastq.gz,FASTQ_DIR/SRR11442232_1.fastq.gz,FASTQ_DIR/SRR11442233_1.fastq.gz,FASTQ_DIR/SRR11442234_1.fastq.gz,FASTQ_DIR/SRR11442235_1.fastq.gz,FASTQ_DIR/SRR11442244_1.fastq.gz,FASTQ_DIR/SRR11442255_1.fastq.gz,FASTQ_DIR/SRR11442256_1.fastq.gz,FASTQ_DIR/SRR11442257_1.fastq.gz", "-2", "FASTQ_DIR/SRR11442128_2.fastq.gz,FASTQ_DIR/SRR11442139_2.fastq.gz,FASTQ_DIR/SRR11442152_2.fastq.gz,FASTQ_DIR/SRR11442163_2.fastq.gz,FASTQ_DIR/SRR11442174_2.fastq.gz,FASTQ_DIR/SRR11442185_2.fastq.gz,FASTQ_DIR/SRR11442196_2.fastq.gz,FASTQ_DIR/SRR11442207_2.fastq.gz,FASTQ_DIR/SRR11442225_2.fastq.gz,FASTQ_DIR/SRR11442226_2.fastq.gz,FASTQ_DIR/SRR11442227_2.fastq.gz,FASTQ_DIR/SRR11442228_2.fastq.gz,FASTQ_DIR/SRR11442229_2.fastq.gz,FASTQ_DIR/SRR11442230_2.fastq.gz,FASTQ_DIR/SRR11442231_2.fastq.gz,FASTQ_DIR/SRR11442232_2.fastq.gz,FASTQ_DIR/SRR11442233_2.fastq.gz,FASTQ_DIR/SRR11442234_2.fastq.gz,FASTQ_DIR/SRR11442235_2.fastq.gz,FASTQ_DIR/SRR11442244_2.fastq.gz,FASTQ_DIR/SRR11442255_2.fastq.gz,FASTQ_DIR/SRR11442256_2.fastq.gz,FASTQ_DIR/SRR11442257_2.fastq.gz", "-t", "18", "-o", "AF_SAMPLE_DIR/pbmc1k_quant/af_map", "--max-ec-card", "4096", "--skipping-strategy", "permissive", "--max-hit-occ", "256", "--max-hit-occ-recover", "1024", "--max-read-occ", "2500"]

[2024-03-06 00:40:48.000] [info] enable structural constraints : false

[2024-03-06 00:40:48.000] [info] No poison k-mer map exists, or it was requested not to be used

[2024-03-06 00:40:48.000] [info] loading index from IDX_DIR/index/piscem_idx

[2024-03-06 00:40:49.420] [info] done loading index

processed (212500000) reads; (170651220) had mappings.fatal runtime error: Rust cannot catch foreign exceptions
====

Error: piscem mapping failed with exit status ExitStatus(unix_wait_status(6))
```

**Comment by rob-p** [comment]
Hi @Anto9393,

  Thanks for reporting this.  The error seems to arise in the `piscem` C++ program, but the status 6 (SIGABORT), unfortunately, isn't super informative.  Three quick questions / thoughts. 

(1) Does this happen with a smaller input set?  If not, is there specific file or number of inputs that trigger it?

(2) Is there a reproducible and sharable subset of this data that we can test on? If we use the SRRs in your example, is that everything? If so, what reference should we be mapping against?

(3) Are you sure of the integrity of all of the files? I ask because it looks like a lot of mapping happened (212M reads processed), and so while some other type of error is of course possible, I wonder if a specific input file is corrupt and failing to parse or, conversely, if there is sufficient output space where you're attempting to write the results.

As always, pinging @DongzeHE here for his input as well.

Thanks,
Rob

**Comment by rob-p** [comment]
Hi @Anto9393,

  I downloaded the data listed in your example, and mapped it against the latest gencode reference.  The run was successful with the following statistics from the mapping command (in `map_info.json`):

```
{
    "cmdline": "sc_ref_mapper -i gencode_v45_idx/index/piscem_idx -g chromium_v2 -1 /ssd2/rob/sc_data/SRR11442128_1.fastq.gz,/ssd2/rob/sc_data/SRR11442139_1.fastq.gz,/ssd2/rob/sc_data/SRR11442152_1.fastq.gz,/ssd2/rob/sc_data/SRR11442163_1.fastq.gz
,/ssd2/rob/sc_data/SRR11442174_1.fastq.gz,/ssd2/rob/sc_data/SRR11442185_1.fastq.gz,/ssd2/rob/sc_data/SRR11442196_1.fastq.gz,/ssd2/rob/sc_data/SRR11442207_1.fastq.gz,/ssd2/rob/sc_data/SRR11442225_1.fastq.gz,/ssd2/rob/sc_data/SRR11442226_1.fastq.gz,
/ssd2/rob/sc_data/SRR11442227_1.fastq.gz,/ssd2/rob/sc_data/SRR11442228_1.fastq.gz,/ssd2/rob/sc_data/SRR11442229_1.fastq.gz,/ssd2/rob/sc_data/SRR11442230_1.fastq.gz,/ssd2/rob/sc_data/SRR11442231_1.fastq.gz,/ssd2/rob/sc_data/SRR11442232_1.fastq.gz,/
ssd2/rob/sc_data/SRR11442233_1.fastq.gz,/ssd2/rob/sc_data/SRR11442234_1.fastq.gz,/ssd2/rob/sc_data/SRR11442235_1.fastq.gz,/ssd2/rob/sc_data/SRR11442244_1.fastq.gz,/ssd2/rob/sc_data/SRR11442255_1.fastq.gz,/ssd2/rob/sc_data/SRR11442256_1.fastq.gz,/s
sd2/rob/sc_data/SRR11442257_1.fastq.gz -2 /ssd2/rob/sc_data/SRR11442128_2.fastq.gz,/ssd2/rob/sc_data/SRR11442139_2.fastq.gz,/ssd2/rob/sc_data/SRR11442152_2.fastq.gz,/ssd2/rob/sc_data/SRR11442163_2.fastq.gz,/ssd2/rob/sc_data/SRR11442174_2.fastq.gz,
/ssd2/rob/sc_data/SRR11442185_2.fastq.gz,/ssd2/rob/sc_data/SRR11442196_2.fastq.gz,/ssd2/rob/sc_data/SRR11442207_2.fastq.gz,/ssd2/rob/sc_data/SRR11442225_2.fastq.gz,/ssd2/rob/sc_data/SRR11442226_2.fastq.gz,/ssd2/rob/sc_data/SRR11442227_2.fastq.gz,/
ssd2/rob/sc_data/SRR11442228_2.fastq.gz,/ssd2/rob/sc_data/SRR11442229_2.fastq.gz,/ssd2/rob/sc_data/SRR11442230_2.fastq.gz,/ssd2/rob/sc_data/SRR11442231_2.fastq.gz,/ssd2/rob/sc_data/SRR11442232_2.fastq.gz,/ssd2/rob/sc_data/SRR11442233_2.fastq.gz,/s
sd2/rob/sc_data/SRR11442234_2.fastq.gz,/ssd2/rob/sc_data/SRR11442235_2.fastq.gz,/ssd2/rob/sc_data/SRR11442244_2.fastq.gz,/ssd2/rob/sc_data/SRR11442255_2.fastq.gz,/ssd2/rob/sc_data/SRR11442256_2.fastq.gz,/ssd2/rob/sc_data/SRR11442257_2.fastq.gz -t
32 -o issue138_quant/af_map --max-ec-card 4096 --skipping-strategy permissive --max-hit-occ 256 --max-hit-occ-recover 1024 --max-read-occ 2500",
    "num_mapped": 308530659,
    "num_poisoned": 0,
    "num_reads": 380470571,
    "percent_mapped": 81.09185900740796,
    "runtime_seconds": 292.0
}
```

So, the issue could be either a corrupted input, insufficient output space, or a system-specific issue arising on your machine or a different reference (if you're using a different reference).  I think the things to check first are the 3 I listed above.

--Rob

**Comment by Anto9393** [comment]
Thank you very much, I have tried with a subset and it works. Now my question is: is it possible to mapp it without using such a memory amount?

**Comment by rob-p** [comment]
The overall memory usage for me was quite low (a few GB, I think ~3G but will check in the morning). Do both disjoint subsets work, or if you try mapping just the remaining files, does it fail? Do you have disk space for the output too? You probably need about 20GB of storage for all the output.

**Comment by Anto9393** [comment]
I have enough space in my disc, i dont know why it is failing, (my pc have 20 nucleis and 64g of ram), I think that it have to be enough, I am working with windows and a wsl for linux display.

In addition now I haveother problem, when I open the count matrix with R Studio, that one that I have made with the subset, and there is not any count, it is completely empty.

**Comment by rob-p** [comment]
Can you share the json files in your output folder? Also, are you using the latest version of simpleaf?

**Comment by rob-p** [comment]
¼0

**Comment by rob-p** [comment]
Hrmm something's not right there. For example there should be separate "map" and "quant" directories in the ouput directory. Also the ouput looks very small. I don't know too much about WSL but is the output being written to the "linux" partition, or the windows filesystem?

**Comment by Anto9393** [comment]
I dont understand this message, it is the version that I should use?

**Comment by Anto9393** [comment]
in the wsl there is not partition, maybe that the problem. I will try with linux

**Comment by rob-p** [comment]
Thanks, @Anto9393. Please let us know when you have a chance to check if this is, indeed, the issue.

Thanks!
Rob

**Comment by Anto9393** [comment]
In addition quants_mat_rows.txt is a 0 bit ...completely empty

**Comment by rob-p** [comment]
I didn't recieve the json file. Can you try and post it here via the web interface? That might not work via email with github.

When you say the same error, do you mean the sigabort?

Thanks,
Rob

**Comment by Anto9393** [comment]
Here you have
[collate.json](https://github.com/COMBINE-lab/alevin-fry/files/14524531/collate.json)
[generate_permit_list.json](https://github.com/COMBINE-lab/alevin-fry/files/14524532/generate_permit_list.json)
[quant.json](https://github.com/COMBINE-lab/alevin-fry/files/14524533/quant.json)

**Comment by Anto9393** [comment]
I have solved the original problem, there is a truncated file in the fastq folder, but now the problem is that the count matrix is empty.

**Comment by rob-p** [comment]
Thanks @Anto9393,

  This is very helpful.  There is one more json file of interest. In your output directory `AF_SAMPLE_DIR/pbmc1k_quant/af_quant`, there should be a subdirectory called `af_map`, and within that directory a file called `map_info.json`. Can you share that? Also, what is the size of the `map.rad` file in that same directory.

Thanks!
Rob

**Comment by Anto9393** [comment]
[map_info.json](https://github.com/COMBINE-lab/alevin-fry/files/14525322/map_info.json)
and map.rad is 1.150Kb

**Comment by rob-p** [comment]
Hi @Anto9393,

Hrmm ... this json file is completely empty, suggesting that it wasn't written properly. 1.15Kb is also way too small.  What reference are you mapping against.  For the record, here's what I did in my successful run on this data:

Get the reference annotation and genome and unzip the genome (that restriction on zipped genomes will soon be removed, but for now the genome needs to be unzipped, the annotation need not be):

```
$ mkdir ref
$ cd ref
$ wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_45/gencode.v45.basic.annotation.gtf.gz
$ wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_45/GRCh38.primary_assembly.genome.fa.gz
$ gunzip GRCh38.primary_assembly.genome.fa.gz
$ cd ..
```

This step need only be done if your open-file limit is very low, but I'm putting it here just to be sure:

```
$ ulimit -n 2048
```

Build the index:

```
$ simpleaf index -o gencode_v45_idx -t 16 -f refs/GRCh38.primary_assembly.genome.fa -g refs/gencode.v45.primary_assembly.annotation.gtf -r 91 --ref-type splici
```

Do the quantification
```
$ simpleaf quant -i gencode_v45_idx/index --reads1 $files1 --reads2 $files2 --threads 32 --chemistry 10xv2 --resolution cr-like --expected-ori fw --unfiltered-pl --t2g-map genco
de_v45_idx/index/t2g_3col.tsv --output issue138_quant
```

where `$files1` and `$files2` are the list of file. In my case:

```
$ echo $files1
/ssd2/rob/sc_data/SRR11442128_1.fastq.gz,/ssd2/rob/sc_data/SRR11442139_1.fastq.gz,/ssd2/rob/sc_data/SRR11442152_1.fastq.gz,/ssd2/rob/sc_data/SRR11442163_1.fastq.gz,/ssd2/rob/sc_data/SRR11442174_1.f
astq.gz,/ssd2/rob/sc_data/SRR11442185_1.fastq.gz,/ssd2/rob/sc_data/SRR11442196_1.fastq.gz,/ssd2/rob/sc_data/SRR11442207_1.fastq.gz,/ssd2/rob/sc_data/SRR11442225_1.fastq.gz,/ssd2/rob/sc_data/SRR1144
2226_1.fastq.gz,/ssd2/rob/sc_data/SRR11442227_1.fastq.gz,/ssd2/rob/sc_data/SRR11442228_1.fastq.gz,/ssd2/rob/sc_data/SRR11442229_1.fastq.gz,/ssd2/rob/sc_data/SRR11442230_1.fastq.gz,/ssd2/rob/sc_data
/SRR11442231_1.fastq.gz,/ssd2/rob/sc_data/SRR11442232_1.fastq.gz,/ssd2/rob/sc_data/SRR11442233_1.fastq.gz,/ssd2/rob/sc_data/SRR11442234_1.fastq.gz,/ssd2/rob/sc_data/SRR11442235_1.fastq.gz,/ssd2/rob
/sc_data/SRR11442244_1.fastq.gz,/ssd2/rob/sc_data/SRR11442255_1.fastq.gz,/ssd2/rob/sc_data/SRR11442256_1.fastq.gz,/ssd2/rob/sc_data/SRR11442257_1.fastq.gz

$ echo $files2 
/ssd2/rob/sc_data/SRR11442128_2.fastq.gz,/ssd2/rob/sc_data/SRR11442139_2.fastq.gz,/ssd2/rob/sc_data/SRR11442152_2.fastq.gz,/ssd2/rob/sc_data/SRR11442163_2.fastq.gz,/ssd2/rob/sc_data/SRR11442174_2.f
astq.gz,/ssd2/rob/sc_data/SRR11442185_2.fastq.gz,/ssd2/rob/sc_data/SRR11442196_2.fastq.gz,/ssd2/rob/sc_data/SRR11442207_2.fastq.gz,/ssd2/rob/sc_data/SRR11442225_2.fastq.gz,/ssd2/rob/sc_data/SRR1144
2226_2.fastq.gz,/ssd2/rob/sc_data/SRR11442227_2.fastq.gz,/ssd2/rob/sc_data/SRR11442228_2.fastq.gz,/ssd2/rob/sc_data/SRR11442229_2.fastq.gz,/ssd2/rob/sc_data/SRR11442230_2.fastq.gz,/ssd2/rob/sc_data
/SRR11442231_2.fastq.gz,/ssd2/rob/sc_data/SRR11442232_2.fastq.gz,/ssd2/rob/sc_data/SRR11442233_2.fastq.gz,/ssd2/rob/sc_data/SRR11442234_2.fastq.gz,/ssd2/rob/sc_data/SRR11442235_2.fastq.gz,/ssd2/rob
/sc_data/SRR11442244_2.fastq.gz,/ssd2/rob/sc_data/SRR11442255_2.fastq.gz,/ssd2/rob/sc_data/SRR11442256_2.fastq.gz,/ssd2/rob/sc_data/SRR11442257_2.fastq.gz
```

In my case, this produces the following output within the quant directory:

```
$ du -h issue138_quant/af_map/*
4.0K    issue138_quant/af_map/map_info.json
11G     issue138_quant/af_map/map.rad
98M     issue138_quant/af_map/unmapped_bc_count.bin
```

```
$ du -h issue138_quant/af_quant/*
96M     issue138_quant/af_quant/alevin
4.0K    issue138_quant/af_quant/collate.json
13M     issue138_quant/af_quant/featureDump.txt
4.0K    issue138_quant/af_quant/generate_permit_list.json
8.9G    issue138_quant/af_quant/map.collated.rad
3.4M    issue138_quant/af_quant/permit_freq.bin
13M     issue138_quant/af_quant/permit_map.bin
28K     issue138_quant/af_quant/quant.json
2.5M    issue138_quant/af_quant/unmapped_bc_count_collated.bin
```

Is there substantial deviation in any part of the process that you're following?

**Comment by Anto9393** [comment]
but it is supose that $ simpleaf index -o gencode_v45_idx -t 16 -f refs/GRCh38.primary_assembly.genome.fa -g refs/gencode.v45.primary_assembly.annotation.gtf -r 91 --ref-type splici      -r 91 have to be the amount of pair base in my sequences no???

**Comment by rob-p** [comment]
so you mean the `91`? That doesn't have to be exactly the case.  This determines the amount of overhang around splice junctions included in the indexed introns. We showed in the `alevin-fry` paper that quantification results are generally very robust to this choice.  Either way, certainly mis-specifying this wouldn't cause a huge difference in mapping rate.  I'd be more concerned that the reference is on the correct annotation and that e.g. the index was constructed correctly.  My index directory looks like the following:


```
$ du -h gencode_v45_idx/index/*
4.0K    gencode_v45_idx/index/piscem_idx_cfish.json
1.1G    gencode_v45_idx/index/piscem_idx.ctab
519M    gencode_v45_idx/index/piscem_idx.ectab
4.0K    gencode_v45_idx/index/piscem_idx.json
8.6M    gencode_v45_idx/index/piscem_idx.refinfo
1.9G    gencode_v45_idx/index/piscem_idx.sshash
4.0K    gencode_v45_idx/index/simpleaf_index.json
13M     gencode_v45_idx/index/t2g_3col.tsv
```

**Comment by Anto9393** [comment]
Thank you very much it works perfectly now. Just for ending the issue, is there a way to quantify the nuclear fraction on the cells? since now I was using the cellranger output and dropletqc thanks

**Comment by DongzeHE** [comment]
Hi @Anto9393,
According to dropletQC, nuclear fraction is defined as 

```
nuclear fraction = intronic reads / (intronic  reads  +  exonic  reads)
```

Yes. You can load the quantification result of alevin-fry into R using the`loadFry` function from [fishpond](https://bioconductor.org/packages/release/bioc/html/fishpond.html). You will need to specify the `outputFormat=scrna`. This will assign all exonic UMIs as spliced UMIs. `loafFry` returns a SingleCellExperiment object containing two assays (count matrices),`Spliced` and `Unspliced`. You can use these two count matrices to compute the nuclear fraction. To be specific, you need to compute the `colSums` of the two count matrices to get the spliced(exonic) and unspliced(intronic) total count of each cell. The nuclear fraction can then be computed by dividing the `colSums` results of the two count matrices. 

The above answer was based on the definition of nuclear fraction. I did not dig into their code to see how they calculate the nuclear fraction. One more thing is that we recommend to use the `emptyDrops` function from [DropletUtils](https://bioconductor.org/packages/release/bioc/html/DropletUtils.html) to detect high-quality cells. 

Finally, I am not sure what you mean by `I was using the cellranger output`. The above answer only works for alevin-fry results, because cellranger cannot return spliced and unspliced count separately. 

Best,
Dongze

**Comment by Anto9393** [comment]
Thank you very much, everything solved.

I was using cellranger before starting with alevin-fry, and the output off
cellranger are different documenta that I can use to feed drolpetqc and
decontx but now i Will use you explanation for doing the qc.

Thank you very much.
