### ISSUE TITLE
read rad file into polars dataframe

### ISSUE THREAD

**Issue by wangjiawen2013** [COMBINE-lab/alevin-fry#147]
Hi,
Can the rad file be read into polars dataframe ?  If so, we can process rad files with customized method.

**Comment by rob-p** [comment]
Hi @wangjiawen2013,

  Do you mean the `featureDump` file to which Yuan referred in the previous issue, or the actual RAD file?  Loading the feature file into a polars or pandas data frame is trivial, as it’s already a tab-separated file, and is usually quite small.

  Loading the RAD file into a data frame would be a much bigger lift, as RAD is the raw data format that contains information on every single alignment of every single read in the experiment.  For even moderate sized experiments, this would be quite a large data frame.

  That said, `alevin-fry` does have a `views` command that writes out the RAD records in a text-based format.  That text-based representation could certainly be read into a data frame if you have sufficient memory to do so.

—Rob

**Comment by wangjiawen2013** [comment]
I mean the actual RAD file. In some cases, I want to subset the rad file. In another case, I want to calculate the umi frequency (the frequency of unique umi, duplicated umi, triplicate umi and so on) distribution per gene per cell. 
There are excellent tools to manipulate bam files, such as samtools, however for alevin-fry, there is a short of tools to manipulate rad files, which restricts of usage flexibility.
And, another question, could we convert bam to rad and convert rad to bam using alevin-fry ?

**Comment by rob-p** [comment]
So in this case, you can, as I said, convert the RAD into a text format and read it into a dataframe.

You're right that there are many more mature tools for interacting with SAM/BAM files than RAD, as it's a much more widely used format.  We do have a [radtk](https://github.com/COMBINE-lab/radtk) repository, but that is currently nascent.  However, we welcome recommendations for new commands / operations there.

It is possible to convert an _appropriately-generated_ BAM file into the RAD format (for the case of single-cell RNA-seq, a BAM file aligned to the transcriptome with the appropriate UMI & BC tags).  However, conversion in the other direction is not supported, at least for the types of RAD files used in the context of single-cell RNA-seq.  The reason for this is that RAD files are **R**educed **A**lignment **D**ata files. They do not contain the same required information as a SAM/BAM file.  For single-cell RNA-seq, in particular, the RAD file contains for each read, the barcode and UMI, and only the identity and orientation with which it maps to each transcript but not e.g. position, CIGAR, or other such information.

Best,
Rob

**Comment by wangjiawen2013** [comment]
Thanks, I think it will be useful to support subsampling and spliting rad files with radtk.

**Comment by rob-p** [comment]
Great suggestions. Could you please open up feature requests for these in the radtk repo so WWE could discuss design and track progress?

Thanks!
Rob

**Comment by wangjiawen2013** [comment]
I have opended an issue in radtk repo.
