### ISSUE TITLE
Fewer true cells detected with alevin-fry.

### ISSUE THREAD

**Issue by YOU-k** [COMBINE-lab/alevin-fry#24]
Hi who's concerning,
I was using alevin-fry with splici index on a 10xv3 pbmc 5K dataset with simpleaf.
Here is my script,
singularity exec --cleanenv \
--bind $singular_p:/workdir \
--pwd /usefulaf/bash usefulaf_latest.sif \
./simpleaf quant \
-1 /workdir/$fastq1 \
-2 /workdir/$fastq2 \
-i /workdir/human_splici/index \
-o /workdir/quants/$project \
-f u -c v3 -r cr-like \
-m /workdir/human_splici/ref/transcriptome_splici_fl86_t2g_3col.tsv \
-t 16

However, I get fewer true cells. Only 3000 cells returned.

I used the old 10x quantile strategy to check.
Here is what I have,
> af_all = load_fry(splici_path)
> counts(af_all)->m
> libs <- colSums(m)
> o <- order(libs, decreasing = TRUE)
> top <- libs[head(o, n = 5000)]
> summary(top)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
     79     156    6352    6028    8877   51043 
> quantile(top, 0.99)
     99% 
24923.19 
> table(libs>quantile(top, 0.99)*0.1)

 FALSE   TRUE 
171451   3171

Any suggestion to solve this?
Cheers,
Yue

**Comment by rob-p** [comment]
Thanks for the report, Yue.

Could you please let us know what specific reference you are using (e.g. is it a 10x-provided reference or something else? If it is, which version, etc.).  In the mean time, I'll also tag @k3yavi and @DongzeHE here to get their take.

**Comment by YOU-k** [comment]
Thanks!
This is how I build the reference:
cd $singular_p
singularity exec --cleanenv \
--bind $singular_p:/workdir \
--pwd /usefulaf/bash usefulaf_latest.sif \
./simpleaf index \
-f /workdir/genome.fa \
-g /workdir/Homo_sapiens.GRCh38.98.gtf \
-l 91 -t 16 -o /workdir/human_splici


Here, genome.fa is the primary assembly genome file for GRCh38 release 98, as well as the gtf file.
They are not from 10x. I download them from Ensembl.
Cheers,
Yue

**Comment by DongzeHE** [comment]
Hi Yue,

Thank you so much for bringing this issue up. 

We first proved that if we run the old 10X quantile strategy on [the count matrix](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.2/5k_pbmc_v3) provided on [10X website](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.2/5k_pbmc_v3), 4571 cells are able to pass the filtering. We also tested that replacing 5000 when computing top with the expected number of cells predicted by the EmptyDrop() function in DropletUtils (which yielded 5148 high-quality cells) gave us exactly the same result (4571).

Then, we ran `simpleaf` on the [10X PBMC5K dataset](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.2/5k_pbmc_v3) using the cr3 reference from 10X using the same command as yours. You can download the reference from [here](https://cf.10xgenomics.com/supp/cell-exp/refdata-cellranger-GRCh38-3.0.0.tar.gz) (https://cf.10xgenomics.com/supp/cell-exp/refdata-cellranger-GRCh38-3.0.0.tar.gz). Surprisingly, this reference resulted in 4586 cells after the old 10X quantile strategy.  This may imply that the reference plays an important role in the selection procedure. 

This is a primary reply, we will look into the difference in the reference genome and get back to you. Thanks for choosing alevin-fry. 


Sincerely,
Alevin-fry team

**Comment by DongzeHE** [comment]
Hi Yue,

We have further tested the dataset by downloading the [raw fastq files](https://cg.10xgenomics.com/samples/cell-exp/3.0.2/5k_pbmc_v3/5k_pbmc_v3_fastqs.tar) from [10X website](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.2/5k_pbmc_v3), then follow your code to run simpleaf pipeline (ref + quant) using all the fastq files (all reads). After filtering by the 10X quantile strategy you provided, we found that there are  4592 cells passed the filtering. 

```R
> sce = load_fry("/mnt/scratch5/pbmc5k_out_ensembl_grch38/quant")
> counts(sce) -> m
> libs <- colSums(m)
> o <- order(libs, decreasing = TRUE)
> top <- libs[head(o, n = 5000)]
> summary(top)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
    734    6200    7882    8767   10340   51043
> quantile(top, 0.99)
     99%
26390.24
> table(libs>quantile(top, 0.99)*0.1)

 FALSE   TRUE
249053   4592
```

 We downloaded the primary assembly genome from http://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/ and the GTF file from http://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/ . As we used the same reference, now we wonder whether the difference is from the fastq files. Could you please share the fastq files you included in this analysis? for us, they are 
```
$ls
5k_pbmc_v3_S1_L001_I1_001.fastq.gz  5k_pbmc_v3_S1_L002_R1_001.fastq.gz  5k_pbmc_v3_S1_L003_R2_001.fastq.gz
5k_pbmc_v3_S1_L001_R1_001.fastq.gz  5k_pbmc_v3_S1_L002_R2_001.fastq.gz  5k_pbmc_v3_S1_L004_I1_001.fastq.gz
5k_pbmc_v3_S1_L001_R2_001.fastq.gz  5k_pbmc_v3_S1_L003_I1_001.fastq.gz  5k_pbmc_v3_S1_L004_R1_001.fastq.gz
5k_pbmc_v3_S1_L002_I1_001.fastq.gz  5k_pbmc_v3_S1_L003_R1_001.fastq.gz  5k_pbmc_v3_S1_L004_R2_001.fastq.gz
```

**Comment by YOU-k** [comment]
Hi there,
Thanks for looking into this,
That's weird. I actually use the same fastq files as you provide here. I concatenate the R1 files, R2 files together separately and they are used as input.
[salmon_quant.log](https://github.com/COMBINE-lab/alevin-fry/files/7071707/salmon_quant.log)
[collate.log](https://github.com/COMBINE-lab/alevin-fry/files/7071708/collate.log)
[gpl.log](https://github.com/COMBINE-lab/alevin-fry/files/7071709/gpl.log)
[quant.log](https://github.com/COMBINE-lab/alevin-fry/files/7071710/quant.log)

I also did this for another dataset, which is a 10xv2 dataset. But the number of reads per cell is quite similar to results from other pipelines. 
I also provide the log files here. Is there any suggestion?
Cheers,
Yue

**Comment by DongzeHE** [comment]
Hi Yue,

We have the same `salmon_quant.log`, but the alevin-fry logs are totally different. It seems like the reason could be that we used different 10X Cellular barcode whitelist file, but this file is downloaded automatically by simpleaf, so we are not sure what happened here. If possible, could you please provide the `gpl/generate_permit_list.json` in the output folder? 

Sincerely,
Alevin-fry team

**Comment by YOU-k** [comment]
No problem! 
Here is the info in the `generate_permit_list.json`
`{
  "cmd": "alevin-fry generate-permit-list -u /workdir/.afhome/plist/10x_v3_permit.txt -d fw -i /workdir/quants/pbmc5k/alevin_map -o /workdir/quants/pbmc5k/gpl/",
  "expected_ori": "+",
  "max-ambig-record": 2395,
  "permit-list-type": "unfiltered",
  "velo_mode": false,
  "version_str": "0.4.0"
}`

Any suggestion?
Cheers,
Yue

**Comment by DongzeHE** [comment]
Can you do a `wc -l` and a `md5sum` on the `10x_v3_permit.txt` file?

**Comment by YOU-k** [comment]
`-bash-4.2$ wc -l 10x_v3_permit.txt`
4662846 10x_v3_permit.txt
`-bash-4.2$ md5sum 10x_v3_permit.txt `
57753c289344293124c150d235265bd8  10x_v3_permit.txt

**Comment by DongzeHE** [comment]
This is very interesting! If you manually run the code that simpleaf used to download the whitelist file, there should be 6794880 lines in the code. Maybe this is caused by internet disruption or something. Could you please try to download the file manually and run simpleaf quant again? To download the whitelist file, you need to run 

```bash
wget -v -O /workdir/.afhome/plist/10x_v3_permit.txt -L https://umd.box.com/shared/static/eo0qlkfqf2v24ws6dfnxty6gqk1otf2h
```  

Sincerely, 
Alevin-fry team

**Comment by YOU-k** [comment]
Good that you help me find the issue!
It works now.
Thanks a lot.
Yue

**Comment by DongzeHE** [comment]
You are very welcome.

**Comment by rob-p** [comment]
I am glad this resolved your issue @YOU-k.  We'll consider putting an md5 check in place in case the connection is interrupted or some such while downloading  the external permit lists!
