### ISSUE TITLE
Can we set barcode and umi ranges manually?

### ISSUE THREAD

**Issue by diyang1354** [COMBINE-lab/alevin-fry#41]
Hi,
Can wen set barcode and umi ranges to support custom single cell protocol? I can't find a way in the tutorial.
If I missed anything in the tutorial, I appologize.
Best,
Di

**Comment by rob-p** [comment]
Hi Di,

  Yes; you can pass custom geometry for the UMI, barcode, and read for subsequent processing with `alevin-fry`.  Strangely, the best documentation for this currently is in the release notes for `salmon` where this feature was added [here](https://github.com/COMBINE-lab/salmon/releases/tag/v1.4.0).  We should add the documentation of this syntax to the documentation proper.  Please let me know if you have any further questions about this.

Best,
Rob
