### ISSUE TITLE
`quickersort` dependency no longer available

### ISSUE THREAD

**Issue by jashephe** [COMBINE-lab/alevin-fry#56]
Upon cloning the main branch and attempting to build `alevin-fry` with `cargo 1.60.0 (d1fd9fe 2022-03-01)` (`rustc 1.60.0 (7737e0b5c 2022-04-04)`), I get the following output:
```
Updating crates.io index
Updating git repository `https://github.com/parazodiac/SingleCellExperiment`
error: no matching package named `quickersort` found
location searched: registry `crates-io`
required by package `alevin-fry v0.5.0 (/scratch/bclab/james/2022.05.10.3T3_libGli2-pool1_10X_spike-in/alevin-fry)`
```

Indeed, [`quickersort` has been yanked from crates.io](https://crates.io/crates/quickersort), and [the project page](https://github.com/notriddle/quickersort) notes:
> There's really no point in using this library any more. Everything good about it has been incorporated into [std::sort_unstable](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.sort_unstable) in the Rust standard library, which even uses a better algorithm. Just use that.

A quick review suggests that `quickersort` is mainly used in `pugutils.rs`, `rad_types.rs`, `eq_class.rs`, and `collate.rs`. `sort_unstable` seems like it ought to be a drop-in replacement for these.

**Comment by rob-p** [comment]
Hi @jashephe,

  You're *quick* (pun intended)!  In fact, this has already been fixed in develop :).  A release of `0.5.1` is due soon (perhaps later today if I get time for it).  In the mean time, please see if you can compile without issue if you pull from the `develop` branch.

Best,
Rob

**Comment by jashephe** [comment]
Thanks Rob, I was able to build from the `develop` branch without any issues.
