### ISSUE TITLE
Avoid any barcode filtering

### ISSUE THREAD

**Issue by nadjano** [COMBINE-lab/alevin-fry#71]
Hello, 

Is there an option to run `alevin-fry generate-permit-list ` without any barcode filtering? 
(Like the `--keepCBFraction 1 `for alevin). 
We would like to run Alevin-fry with running EmptyDrops() afterwards. 

As I understand the two options are:
1.  Use `--unfiltered-pl whitelist `with `--min-reads 0`
2.  set `--force-cells really high`

Thank you!

Best, 
Nadja

**Comment by rob-p** [comment]
Hi @nadjano,

  That is correct. The most straightforward way would be to use option 1.  However, I'll mention that the default `--min-reads` filter is quite liberal (10).  Also, note, this is the number of *reads* not *UMIs*.  We simply found that many samples contain a very long tail of cells with 1 or 2 reads, and excluding them has not measurable effect on downstream analysis.  That said, if you want to quantify everything — even cells with only a single read — then option 1 is your best bet if you are dealing with protocols having an external permit list (e.g. 10x chromium) while option 2 is what you would use if no external permit-list is available.

Best,
Rob

**Comment by nadjano** [comment]
Thanks a lot @rob-p!
