### ISSUE TITLE
doc on read geometry

### ISSUE THREAD

**Issue by fransua** [COMBINE-lab/alevin-fry#94]
Hi,
I cannot find clear help on read_geometry. There are a couple of examples but they do not seem to work for me and I am struggling to change them.
Specifically I have several questions:
 - what does the "read_geometry" refers to? I saw that it is usually set to "2[1-end]", but why only read 2, and when does the whole read is not a read?
 - what is the pattern of inclusion exclusion? 1-10 starts at the first nucleotide but includes the ninth or the tenth too?
 - How does alevin-fry deals with unexact position, for instance in my case the cell tag can start anywhere between position 85 and 115 because of a variable polyA before.

thanks

**Comment by rob-p** [comment]
Hi @fransua,

  The geometry tag describes how the UMI, cell barcode, and "biological" read sequence are parsed during the mapping phase (upstream of `alevin-fry`).  Therefore, the most appropriate place to address these queries is in the GitHub issues for the `salmon` repository.  I will repost this there and tag you.

  As to your last question — salmon can deal with inexact locations for barcodes / UMIs, but that is an "advanced" geometry setting that is not yet in the released version of the tool (basically, where one can describe the sequence motif that must occur upstream of the barcode and UMI).  If you can describe your protocol there a bit more, we could implement a custom flag for it to parse the information for such reads. Alternatively, you can use another package (e.g. UMI-tools) to "normalize" the barcode and umi geometry into a simpler format that can be directly handled by salmon.
  
Best,
Rob
